global:
    sendAnonymousUsage: false

entryPoints:
    web:
        address: :80

providers:
    docker:
        exposedByDefault: false
        defaultRule: "Host(`{{ normalize .Name }}.docker.localhost`)"
        network: traefik
    file:
        filename: "/etc/traefik/traefik_dynamic.yml"

api: {}

log:
    level: DEBUG
